### ISSUE TITLE
Loss computation target

### ISSUE THREAD

**Issue by kgeorgid** [bwconrad/decoder-denoising#3]
Hello, shouldn't the target in the loss function be the input image, instead of the noise?
https://github.com/bwconrad/decoder-denoising/blob/1bfa5838df193069df4ffe7465f9039f49a4f7f1/src/model.py#L122
Since the task is denoising, it would be more intuitive. Also, the final predicted image is not computed anywhere.

**Comment by bwconrad** [comment]
This work is inspired by recent diffusion models which have found that it is empirically better to predict the noise instead of the original image when learning the denoising task. This is explained in section 3.2 of the paper. The predicted noise-less image can be reconstructed by subtracting the predicted noise from the input image.   

![image](https://user-images.githubusercontent.com/16932085/200899866-1ed46f32-f910-4de8-bf8b-387181897e87.png)

**Comment by kgeorgid** [comment]
Thank you for the clarification! My intended models have this direct skip connection from the input, so I suppose the result would be the same, but I will try both approaches anyway!
