### ISSUE TITLE
What is your experimental environment?

### ISSUE THREAD

**Issue by Haoyu-Xie** [bwconrad/decoder-denoising#4]
How much GPU memory is required for basics?

**Comment by bwconrad** [comment]
When I did my experiments, I was doing decoder-only pretraining on a U-Net with a ResNet-50 encoder and batch size of 256 on a single 3090 (24GB) and had memory to spare. Since decoders don't have a lot of parameters, when doing decoder-only pretraining the memory requirement is not that bad since the encoder is kept frozen.

**Comment by Haoyu-Xie** [comment]
> 

It is so cheap in memory! 
Thanks for your kind reply.
