### ISSUE TITLE
Can I use your code on classification task? Directly use the encoder that you designated.

### ISSUE THREAD

**Issue by byerose** [bwconrad/decoder-denoising#5]

**Comment by bwconrad** [comment]
Yes, it is possible to use just the encoder and fine-tune it on a classification task. Just make sure that during denoising pretraining that you have `--model.mode "encoder+decoder"` or else the encoder will be kept frozen during pretraining.

Once you've finished pretraining, you can load the encoder weights with something like this:
```python
import torch
from torchvision.models import resnet50

# Load entire state_dict
checkpoint = torch.load("dep-unet-resnet50.ckpt", map_location="cpu")["state_dict"]

# Keep only encoder weights
encoder_weights = {}
for k, v in checkpoint.items():
    if not k.startswith("net.encoder."):
        continue

    k = k.replace("net.encoder.", "")
    encoder_weights[k] = v

# Initialize new network with the weights
encoder = resnet50()
encoder.load_state_dict(encoder_weights, strict=False)
```
`strict=False` is used since the final classification layer will be missing
